/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/42/login": {
    /**
     * Initiate 42 OAuth2 login
     * @description Redirects the user to the 42 authorization endpoint to begin the OAuth2 flow.
     */
    get: operations["initiate42OAuth"];
  };
  "/auth/42/callback": {
    /**
     * 42 OAuth2 callback
     * @description The endpoint that 42 redirects to after authentication. Handles the OAuth flow,
     * creates a session, and redirects to the frontend with a session cookie set.
     */
    get: operations["handle42OAuthCallback"];
  };
  "/auth/status": {
    /**
     * Get current authentication status
     * @description Returns the currently logged-in user's information based on their session.
     */
    get: operations["getAuthStatus"];
  };
  "/auth/logout": {
    /**
     * Log out the current user
     * @description Invalidates the user's session and clears the session cookie.
     */
    post: operations["logoutUser"];
  };
  "/auth/2fa/generate": {
    /**
     * Generate a new 2FA secret & QR code
     * @description Generates a new TOTP secret for the authenticated user and returns a QR code
     * for easy setup with an authenticator app. This does NOT enable 2FA.
     */
    post: operations["generate2FASecret"];
  };
  "/auth/2fa/enable": {
    /**
     * Enable Two-Factor Authentication
     * @description Verifies the provided TOTP code against the generated secret.
     * If successful, enables 2FA for the user's account.
     */
    post: operations["enable2FA"];
  };
  "/users/me": {
    /**
     * Get current user profile
     * @description Retrieve the complete profile of the currently authenticated user.
     */
    get: operations["getCurrentUser"];
    /**
     * Update current user profile
     * @description Update the username or avatar of the currently authenticated user.
     */
    patch: operations["updateCurrentUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      /**
       * Format: uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /** @example great_ponger */
      username: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: uri
       * @example /avatars/user1.png
       */
      avatar?: string | null;
      /** @example false */
      is2FAEnabled: boolean;
      /**
       * @example ONLINE
       * @enum {string}
       */
      status: "ONLINE" | "OFFLINE" | "INGAME";
      /** Format: date-time */
      createdAt: string;
    };
    Enable2FARequest: {
      /**
       * @description The TOTP code from the user's authenticator app
       * @example 123456
       */
      code: string;
    };
    TwoFactorSecret: {
      /**
       * @description The TOTP secret key for manual entry
       * @example JBSWY3DPEHPK3PXP
       */
      secret?: string;
      /**
       * @description A data URL containing a QR code image
       * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACt...
       */
      qrCode?: string;
    };
    UpdateUserRequest: {
      /** @example new_username */
      username?: string;
      /**
       * Format: binary
       * @description An image file to upload as an avatar
       */
      avatar?: string;
    };
    ErrorResponse: {
      /** @example Invalid authentication code */
      error?: string;
      /** @example 2FA_INVALID_CODE */
      code?: string;
      details?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Initiate 42 OAuth2 login
   * @description Redirects the user to the 42 authorization endpoint to begin the OAuth2 flow.
   */
  initiate42OAuth: {
    responses: {
      /** @description Redirect to 42's OAuth2 authorization page. */
      302: {
        headers: {
          /** @example https://api.intra.42.fr/oauth/authorize?client_id=your-client-id&redirect_uri=https%3A%2F%2Fapi.transcendence.local%2Fapi%2Fauth%2F42%2Fcallback&response_type=code */
          Location?: string;
        };
        content: never;
      };
    };
  };
  /**
   * 42 OAuth2 callback
   * @description The endpoint that 42 redirects to after authentication. Handles the OAuth flow,
   * creates a session, and redirects to the frontend with a session cookie set.
   */
  handle42OAuthCallback: {
    parameters: {
      query: {
        /** @description The authorization code returned by 42 */
        code: string;
        /** @description Error parameter from 42 OAuth */
        error?: string;
        /** @description Error description from 42 OAuth */
        error_description?: string;
      };
    };
    responses: {
      /**
       * @description Redirect to the frontend application upon successful authentication.
       * Sets a session cookie via the API Gateway.
       */
      302: {
        headers: {
          /** @example https://transcendence.local/dashboard */
          Location?: string;
          /** @example session_id=abc123; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=3600 */
          "Set-Cookie"?: string;
        };
        content: never;
      };
      /** @description Invalid OAuth parameters */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get current authentication status
   * @description Returns the currently logged-in user's information based on their session.
   */
  getAuthStatus: {
    responses: {
      /** @description Successfully retrieved the authenticated user. */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description User is not authenticated. No valid session found. */
      401: {
        content: never;
      };
    };
  };
  /**
   * Log out the current user
   * @description Invalidates the user's session and clears the session cookie.
   */
  logoutUser: {
    responses: {
      /** @description Successfully logged out. Session destroyed. */
      204: {
        headers: {
          /** @example session_id=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly */
          "Set-Cookie"?: string;
        };
        content: never;
      };
      /** @description User is not authenticated. */
      401: {
        content: never;
      };
    };
  };
  /**
   * Generate a new 2FA secret & QR code
   * @description Generates a new TOTP secret for the authenticated user and returns a QR code
   * for easy setup with an authenticator app. This does NOT enable 2FA.
   */
  generate2FASecret: {
    responses: {
      /** @description Successfully generated 2FA secret. */
      200: {
        content: {
          "application/json": components["schemas"]["TwoFactorSecret"];
        };
      };
      /** @description User is not authenticated. */
      401: {
        content: never;
      };
    };
  };
  /**
   * Enable Two-Factor Authentication
   * @description Verifies the provided TOTP code against the generated secret.
   * If successful, enables 2FA for the user's account.
   */
  enable2FA: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Enable2FARequest"];
      };
    };
    responses: {
      /** @description 2FA was successfully enabled. */
      200: {
        content: never;
      };
      /** @description The provided TOTP code is invalid. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description User is not authenticated. */
      401: {
        content: never;
      };
    };
  };
  /**
   * Get current user profile
   * @description Retrieve the complete profile of the currently authenticated user.
   */
  getCurrentUser: {
    responses: {
      /** @description Successfully retrieved user profile. */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description User is not authenticated. */
      401: {
        content: never;
      };
    };
  };
  /**
   * Update current user profile
   * @description Update the username or avatar of the currently authenticated user.
   */
  updateCurrentUser: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Successfully updated user profile. */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Invalid input (e.g., username already taken). */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description User is not authenticated. */
      401: {
        content: never;
      };
    };
  };
}
